### ISSUE TITLE
otel.SetLogger or otel.SetLoggerProvider?

### ISSUE THREAD

**Issue by gcsfred2** [agoda-com/opentelemetry-logs-go#16]
On the code example in README.md

# Question
The code example in README.md has
`otel.SetLoggerProvider(loggerProvider)`
 but the function is 
 `[func SetLogger(logger logr.Logger)](https://pkg.go.dev/go.opentelemetry.io/otel#SetLogger)`

# Suggestion (Optional)

Consider changing the example.

**Comment by chameleon82** [comment]
Example is correct. The method you are pointing to is for internal logging only
