### ISSUE TITLE
autoconfigure emit error even when exporter is initilaized successfully

### ISSUE THREAD

**Issue by blumamir** [agoda-com/opentelemetry-logs-go#20]
Hi,
Thanks for sharing and maintaining this repo.

When I use the `autoconfigure` package, I get these errors in my console:
```
2023/10/10 13:51:17 internal_logging.go:58: "msg"="Can't instantiate otlp exporter" "error"=null
```

I checked the code, and it seems that [this line](https://github.com/agoda-com/opentelemetry-logs-go/blob/3defe69e69e483c311140b966f12c535e7b9a854/autoconfigure/sdk/logs/provider.go#L77) (along with the one for the logging exporter [here](https://github.com/agoda-com/opentelemetry-logs-go/blob/3defe69e69e483c311140b966f12c535e7b9a854/autoconfigure/sdk/logs/provider.go#L81)) are emitting errors even when `err` is nil. my sdk setup is able to export log records successfully even with this console error.

I hope I am not missing something obvious, but should these prints be wrapped in an `if` statement? and should the code skip executing `cfg.processors = append(cfg.processors, sdk.NewBatchLogRecordProcessor(otlpExporter))` in case of an error in `otlplogs.NewExporter(ctx)`?

**Comment by chameleon82** [comment]
@blumamir please check if it fixed now with `v0.4.1` release
