### ISSUE TITLE
`HandlerOptions.level` is unexported for `slog`

### ISSUE THREAD

**Issue by Nikola-Milovic** [agoda-com/opentelemetry-logs-go#32]
This is the definition of the `HandlerOptions` for `func NewOtelHandler(loggerProvider otel.LoggerProvider, opts *HandlerOptions) *OtelHandler {`

Which means that you cannot set the level since its unexported :/

```golang
type HandlerOptions struct {
	level slog.Leveler
}
```

https://github.com/agoda-com/opentelemetry-go/blob/main/otelslog/otel_handler.go#L42

**Comment by chameleon82** [comment]
Fixed in latest release https://github.com/agoda-com/opentelemetry-go/releases/tag/otelslog%2Fv0.1.1
